'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Gymnast', [
      {
        gsa_id: '455613',
        first_name: 'Alice',
        last_name: 'Smith',
        date_of_birth: '2008-03-22',
        club: 'Gym Club A',
        district: 'District A',
        contact_number: '123-456-7890',
        ethnicity: 'Caucasian',
        group_id: 1,
        level: "1",
        age: "7-8",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '897654',
        first_name: 'Bob',
        last_name: 'Johnson',
        date_of_birth: '2009-06-15',
        club: 'Gym Club B',
        district: 'District B',
        contact_number: '234-567-8901',
        ethnicity: 'Black',
        group_id: 1,
        level: "1",
        age: "7-8",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '742313',
        first_name: 'Charlie',
        last_name: 'Williams',
        date_of_birth: '2010-08-30',
        club: 'Gym Club C',
        district: 'District C',
        contact_number: '345-678-9012',
        ethnicity: 'Caucasian',
        group_id: 2,
        level: "1",
        age: "9-10",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '354344',
        first_name: 'Diana',
        last_name: 'Brown',
        date_of_birth: '2007-12-10',
        club: 'Gym Club A',
        district: 'District A',
        contact_number: '456-789-0123',
        ethnicity: 'Black',
        group_id: 2,
        level: "1",
        age: "9-10",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '456846',
        first_name: 'Ethan',
        last_name: 'Jones',
        date_of_birth: '2009-07-25',
        club: 'Gym Club B',
        district: 'District B',
        contact_number: '567-890-1234',
        ethnicity: 'Caucasian',
        group_id: 1,
        level: "1",
        age: "7-8",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '549879',
        first_name: 'Fiona',
        last_name: 'Garcia',
        date_of_birth: '2011-09-18',
        club: 'Gym Club C',
        district: 'District C',
        contact_number: '678-901-2345',
        ethnicity: 'Caucasian',
        group_id: 1,
        level: "1",
        age: "7-8",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '465431',
        first_name: 'George',
        last_name: 'Martinez',
        date_of_birth: '2008-11-05',
        club: 'Gym Club A',
        district: 'District A',
        contact_number: '789-012-3456',
        ethnicity: 'Black',
        group_id: 2,
        level: "1",
        age: "9-10",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '135497',
        first_name: 'Hannah',
        last_name: 'Hernandez',
        date_of_birth: '2010-04-12',
        club: 'Gym Club B',
        district: 'District B',
        contact_number: '890-123-4567',
        ethnicity: 'Black',
        group_id: 2,
        level: "1",
        age: "9-10",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '768454',
        first_name: 'Ian',
        last_name: 'Lee',
        date_of_birth: '2009-01-20',
        club: 'Gym Club C',
        district: 'District C',
        contact_number: '901-234-5678',
        ethnicity: 'Caucasian',
        group_id: 1,
        level: "1",
        age: "7-8",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '786613',
        first_name: 'Jane',
        last_name: 'Perez',
        date_of_birth: '2011-05-27',
        club: 'Gym Club A',
        district: 'District A',
        contact_number: '012-345-6789',
        ethnicity: 'Black',
        group_id: 1,
        level: "1",
        age: "7-8",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '675432',
        first_name: 'Kevin',
        last_name: 'Harris',
        date_of_birth: '2009-11-22',
        club: 'Gym Club D',
        district: 'District D',
        contact_number: '101-234-5678',
        ethnicity: 'Asian',
        group_id: 3,
        level: "1",
        age: "11-12",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '784512',
        first_name: 'Laura',
        last_name: 'Clark',
        date_of_birth: '2010-02-14',
        club: 'Gym Club E',
        district: 'District E',
        contact_number: '202-345-6789',
        ethnicity: 'Hispanic',
        group_id: 3,
        level: "1",
        age: "11-12",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '897123',
        first_name: 'Michael',
        last_name: 'Lewis',
        date_of_birth: '2008-08-09',
        club: 'Gym Club F',
        district: 'District F',
        contact_number: '303-456-7890',
        ethnicity: 'Caucasian',
        group_id: 3,
        level: "1",
        age: "11-12",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '984512',
        first_name: 'Nancy',
        last_name: 'Walker',
        date_of_birth: '2007-04-30',
        club: 'Gym Club G',
        district: 'District G',
        contact_number: '404-567-8901',
        ethnicity: 'Black',
        group_id: 3,
        level: "1",
        age: "11-12",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '875123',
        first_name: 'Olivia',
        last_name: 'Hall',
        date_of_birth: '2011-07-21',
        club: 'Gym Club H',
        district: 'District H',
        contact_number: '505-678-9012',
        ethnicity: 'Asian',
        group_id: 3,
        level: "1",
        age: "11-12",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '975213',
        first_name: 'Paul',
        last_name: 'Young',
        date_of_birth: '2010-05-19',
        club: 'Gym Club I',
        district: 'District I',
        contact_number: '606-789-0123',
        ethnicity: 'Hispanic',
        group_id: 3,
        level: "1",
        age: "11-12",
        gender: "M",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        gsa_id: '494645',
        first_name: 'Poppy',
        last_name: 'Flower',
        date_of_birth: '2009-05-19',
        club: 'Gym Club A',
        district: 'District B',
        contact_number: '606-789-0123',
        ethnicity: 'Caucasian',
        group_id: 4,
        level: "1",
        age: "13-14",
        gender: "F",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Gymnast', null, {});
  }
};